services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: sigiswald
      POSTGRES_PASSWORD: pw1234
      POSTGRES_DB: test_db
    volumes:
      - /home/sigiswald/projects/v01/psql_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
